name: rallymobile
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^0.13.6
  flutter_secure_storage: ^8.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/icons/iconapp.jpg"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Noto Sans Thai
      fonts:
        - asset: assets/fonts/NotoSansThai-Regular.ttf
        - asset: assets/fonts/NotoSansThai-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansThai-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansThai-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansThai-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansThai-Black.ttf
          weight: 900
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Thin.ttf
        - asset: assets/fonts/Kanit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Kanit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Kanit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kanit-Black.ttf
          weight: 900
